### ISSUE TITLE
some error for code setup

### ISSUE THREAD

**Issue by haikangdiao** [KULeuven-MICAS/zigzag-imc#7]
when I run the code to test the DIMC with: "python main_onnx.py --model zigzag/inputs/examples/workload/mlperf_tiny/ds_cnn.onnx --accelerator zigzag.inputs.examples.hardware.Dimc --mapping zigzag.inputs.examples.mapping.default_imc".  There is some error: "get_cacti_cost +470 - CRITICAL - CACTI failed. [current setting] rows: 32.0, bw: 32, mem size (byte): 128.0"

I find this error in the "~/zigzag-imc-master/zigzag/classes/hardware/architecture/get_cacti_cost.py". So, could you help me to solve this error?

**Comment by JiacongSun** [comment]
Hi haikangdiao,

Thank you for your interest!

I have successfully tested the code with the same command on my end, and it completed without any error. It appears that there might be some configration issues with CACTI in your environment, as the warning is trigged only when the output file from CACTI is missing.

To debug the problem, you can comment out the `except` block in `get_cacti_cost.py` from line `+468` to `+473`. This will allow you to directly receive the error message from CACTI in the prompt, and then you could debug based on the message.

Feel free to reach out if you encounter any difficulties in resolving it!

Best regards,
Jiacong
