### ISSUE TITLE
zigzag-imc supports multi-macro mapping

### ISSUE THREAD

**Issue by Z-KN** [KULeuven-MICAS/zigzag-imc#9]
I see the configuration for IMC:
```
    dimensions = {
        "D1": 4,    # wordline dimension
        "D2": 32,   # bitline dimension
        "D3": 1,    # nb_macros (nb_arrays)
    }  # e.g. {"D1": ("K", 4), "D2": ("C", 32),}
```
And actually D3 can be other than 1, such as 16. So zigzag-imc actually supports multi-macro mapping, though the paper only showcase 1 macro. Is that right?

**Comment by JiacongSun** [comment]
Hi Z-KN,

Yes, that's correct. ZigZag-IMC can indeed support multiple hardware dimensions. You have the flexibility to define D3 with other integer values (such as 4, 5, 10), and you can also define additional dimensions (such as D4, D5, and beyond).

While the paper primarily focuses on presenting modeling details, this feature is indeed supported, even though it is not explicitly illustrated in the paper.

Best regards,
Jiacong

**Comment by Z-KN** [comment]
But I don't see how can one specify the network topology for multi-macro IMC chips. Does the overall latency include the data transmission among macros? What is the bandwidth of each link?

**Comment by JiacongSun** [comment]
Hi,

I don't see this as a dataflow difficult to map onto the hardware. You can look for some IMC papers with multiple IMC macros in their systems. Inituitively, you can assign different layers' dimensions to different macros to run in parallel.

The model output will take into account the data transmission among macros. As for how the data is communicated across  macros, it entirely depends on your architecture. For instance, you can let the same inputs propagate across different macros, or you can map different inputs onto different macros.

As for the bandwidth, it depends on your `bw` setting of the memory port/link for the memory instances.

**Comment by Z-KN** [comment]
What I mean is that, how to model the interconnection of IMC macros. E.g., this tool supports a 4D tensor to specify the macros, but how are they actually organized? In a flattened mesh, or in a hierarchical way, or through a bus, or an array of a 3D stacking? For each of the architecture, the data transmission pattern and latency is different.

I refer bandwidth as the data rate of on-chip links, not memory ports. E.g., if one macro is going to transmit data to another bank directly through routers on a NoC, where should I specify those. One example would be https://ieeexplore.ieee.org/document/9580448. Could you show case how you model this architecture with Zigzag-imc? Dimension is (4,4) obviously, say the NoC is 8b/cycle/hop/wire.

**Comment by JiacongSun** [comment]
Hi,

ZigZag supports a single-core system architecture where multiple macros share the same memory hierarchy. The architecture you mentioned refers to multi-core systems, where each core possesses its own memory hierarchy.

The data connection across different cores, including how data is linked across the NoC and the transmission rate, is not modeled in ZigZag but in Stream. Please have a check on the [Stream](https://github.com/KULeuven-MICAS/stream) framework for this purpose.

The Stream framework serves as a model for both heterogeneous and homogeneous multicore architectures, in which ZigZag is called for single-core performance estimation. It is being actively maintained primarily for pure digital accelerators. However, IMC cores are also supported within this framework and you can try some experiments there.

**Comment by Z-KN** [comment]
Understood. Thank you!
